### PR TITLE
Fix message parsing not taking into account type namespace

### LINKED ISSUE #39: Types with same name are mixed up
**Description**
When parsing multiple types with the same name, such as `visualization_msgs/Marker` and `aruco_msgs/Marker`, the library mixes them up when they are used as children of another type.

- Version: 4.2.2 (I tested with several versions from 1.0.1 to 4.2.2 and the bug seems to be present in all of them)
- Platform: Linux, ROS noetic (but this probably hits ROS2 too)

**Steps To Reproduce**
```typescript
  let res = parse(`

MSG: visualization_msgs/Marker
int32 a

===
MSG: aruco_msgs/Marker
int32 b

===
MSG: visualization_msgs/MarkerArray
Marker[] a

===
MSG: aruco_msgs/MarkerArray
Marker[] b
  
  `, { ros2: false })

  console.log(JSON.stringify(res, undefined, 2));
```

**Expected Behavior**
`aruco_msgs/MarkerArray` should contain an array of `aruco_msgs/Marker`, not `visualization_msgs/Marker`.

```json
[
  {
    "name": "visualization_msgs/Marker",
    "definitions": [
      {
        "type": "int32",
        "isArray": false,
        "name": "a",
        "isComplex": false
      }
    ]
  },
  {
    "name": "aruco_msgs/Marker",
    "definitions": [
      {
        "type": "int32",
        "isArray": false,
        "name": "b",
        "isComplex": false
      }
    ]
  },
  {
    "name": "visualization_msgs/MarkerArray",
    "definitions": [
      {
        "type": "visualization_msgs/Marker",
        "isArray": true,
        "name": "a",
        "isComplex": true
      }
    ]
  },
  {
    "name": "aruco_msgs/MarkerArray",
    "definitions": [
      {
        "type": "aruco_msgs/Marker",
        "isArray": true,
        "name": "b",
        "isComplex": true
      }
    ]
  }
]
```

**Actual behavior**
Both `MarkerArray` types contain an array of `visualization_msgs/Marker`.

```json
[
  {
    "name": "visualization_msgs/Marker",
    "definitions": [
      {
        "type": "int32",
        "isArray": false,
        "name": "a",
        "isComplex": false
      }
    ]
  },
  {
    "name": "aruco_msgs/Marker",
    "definitions": [
      {
        "type": "int32",
        "isArray": false,
        "name": "b",
        "isComplex": false
      }
    ]
  },
  {
    "name": "visualization_msgs/MarkerArray",
    "definitions": [
      {
        "type": "visualization_msgs/Marker",
        "isArray": true,
        "name": "a",
        "isComplex": true
      }
    ]
  },
  {
    "name": "aruco_msgs/MarkerArray",
    "definitions": [
      {
        "type": "visualization_msgs/Marker",
        "isArray": true,
        "name": "b",
        "isComplex": true
      }
    ]
  }
]
```

### PR DESCRIPTION
**Pull request by achim-k**
### Public-Facing Changes

Fix message parsing not taking into account type namespace

### Description
When resolving a relative type, message parsing did not take into account the namespace of the type, resulting in potentially wrong message definitions when there were two types with the same name but different namespaces.

Fixes #39
Resolves FG-5264

### CODE REVIEW

File: src/parse.ts [hunk 1]
```diff
@@ -141,7 +148,11 @@ function findTypeByName(types: MessageDefinition[], name: string): MessageDefini
     }
     // return if the search is in the type name
     // or matches exactly if a fully-qualified name match is passed to us
-    const nameEnd = name.includes("/") ? name : `/${name}`;
+    const nameEnd = name.includes("/")
+      ? name
+      : typeNamespace
+      ? `${typeNamespace}/${name}`
+      : `/${name}`;
     return typeName.endsWith(nameEnd);
```
Comment (jtbandes) [inline src/parse.ts:156]: This logic seems weird. Based on the comment, I would expect something more like `if (name.includes("/")) { return typeName === name } ...`

File: src/parse.ts [hunk 2]
```diff
@@ -85,10 +85,13 @@ export function parse(messageDefinition: string, options: ParseOptions = {}): Me
 }
 
 export function fixupTypes(types: MessageDefinition[]): void {
```
Comment (jtbandes) [inline src/parse.ts:87]: could we add a comment to describe what this function is supposed to be doing?

Comment (jtbandes) [reply src/parse.ts:87]: Also, I see that there is a `skipTypeFixup` option which skips calling this function. Do we still need to do anything to fix namespace-confusion bugs if `skipTypeFixup: true` is used?

File: src/parse.ts (hunk 1 above)
Comment (achim-k) [reply src/parse.ts]: You are right, rewrote it to make it clearer and match exactly if the type is a FQN (or can be made to a FQN when the namespace is given)

File: src/parse.ts (hunk 2 above)
Comment (achim-k) [reply src/parse.ts:91]: > Like [here](https://github.com/foxglove/rosmsg/blob/5cd65f9092b6b8b6783b5a92678efbeea5297928/src/gendeps2.ts#L83)? but maybe it is already handled correctly?

Looks like the lines below that referenced line are doing more or less the same as what `fixupTypes` does. https://github.com/foxglove/rosmsg/blob/5cd65f9092b6b8b6783b5a92678efbeea5297928/src/gendeps2.ts#L84-L89

**Review by jtbandes — APPROVED** [review]
